<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jasmine Kobayashi &amp; Uday Gadge">

<title>ExoPlanetAnalysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="ExoPlanetAnalysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="ExoPlanetAnalysis_files/libs/quarto-html/quarto.js"></script>
<script src="ExoPlanetAnalysis_files/libs/quarto-html/popper.min.js"></script>
<script src="ExoPlanetAnalysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ExoPlanetAnalysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="ExoPlanetAnalysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ExoPlanetAnalysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ExoPlanetAnalysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ExoPlanetAnalysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ExoPlanetAnalysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ExoPlanetAnalysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jasmine Kobayashi &amp; Uday Gadge </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="nasa-exoplanet-archive" class="level1">
<h1>NASA Exoplanet Archive</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Exo planets are planets that are outside our solar system. The existence of such planets was formulated in 1917, but they were first discovered in 1992. As of December 2022, 5284 exo planets have been confirmed. There is a bias that the discovery methods favor planets that are near the star.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>We got the data from NASA Exo planet archives. The data is a comprehensive list of the exo planets discovered, the time and method of discovery along with the features associated with the planets like mass, radius, orbit length, orbital period etc.,</p>
<p><a href="https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&amp;config=PSCompPars">Link for the data</a></p>
<div class="cell">

</div>
<section id="getting-the-data." class="level3">
<h3 class="anchored" data-anchor-id="getting-the-data.">Getting the data.</h3>
<p>The following loaded dataset was first manually downloaded as a csv file from the previously mentioned NASA planet archives. (Most recent download date: December 7th, 2022). From what we’ve found, most dataset archives for the space sciences or NASA typically provide data to be accessed this way, and we were unable to webscrape the data directly from the link. So, to comply with the project’s reproducibility criteria, the data is loaded from the GitHub repo for this project.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/Rokkaan5/5301-project-test/main/data/PSCompPars_2022.12.07_15.29.01.csv?token=GHSAT0AAAAAAB3GS64J5Y4EH3UOGIIULXQAY4RJZ4Q"</span>   <span class="co"># place holder for GitHub data extraction</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>planet_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url,<span class="at">skip=</span><span class="dv">88</span>,<span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(planet_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 85
  loc_rowid pl_name    hostname sy_snum sy_pnum discov…¹ disc_…² disc_…³ pl_co…⁴
      &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
1         1 11 Com b   11 Com         2       1 Radial …    2007 Xinglo…       0
2         2 11 UMi b   11 UMi         1       1 Radial …    2009 Thueri…       0
3         3 14 And b   14 And         1       1 Radial …    2008 Okayam…       0
4         4 14 Her b   14 Her         1       2 Radial …    2002 W. M. …       0
5         5 16 Cyg B b 16 Cyg B       3       1 Radial …    1996 Multip…       0
6         6 17 Sco b   17 Sco         1       1 Radial …    2020 Lick O…       0
# … with 76 more variables: pl_orbper &lt;dbl&gt;, pl_orbpererr1 &lt;dbl&gt;,
#   pl_orbpererr2 &lt;dbl&gt;, pl_orbperlim &lt;dbl&gt;, pl_orbsmax &lt;dbl&gt;,
#   pl_orbsmaxerr1 &lt;dbl&gt;, pl_orbsmaxerr2 &lt;dbl&gt;, pl_orbsmaxlim &lt;dbl&gt;,
#   pl_rade &lt;dbl&gt;, pl_radeerr1 &lt;dbl&gt;, pl_radeerr2 &lt;dbl&gt;, pl_radelim &lt;dbl&gt;,
#   pl_radj &lt;dbl&gt;, pl_radjerr1 &lt;dbl&gt;, pl_radjerr2 &lt;dbl&gt;, pl_radjlim &lt;dbl&gt;,
#   pl_bmasse &lt;dbl&gt;, pl_bmasseerr1 &lt;dbl&gt;, pl_bmasseerr2 &lt;dbl&gt;,
#   pl_bmasselim &lt;dbl&gt;, pl_bmassj &lt;dbl&gt;, pl_bmassjerr1 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataset dimensions</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(planet_data)  <span class="co"># n-rows x n-columns </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5220   85</code></pre>
</div>
</div>
<p>This particular dataset has 5220 exo planets and 84 properties associated with each planet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(planet_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "loc_rowid"       "pl_name"         "hostname"        "sy_snum"        
 [5] "sy_pnum"         "discoverymethod" "disc_year"       "disc_facility"  
 [9] "pl_controv_flag" "pl_orbper"       "pl_orbpererr1"   "pl_orbpererr2"  
[13] "pl_orbperlim"    "pl_orbsmax"      "pl_orbsmaxerr1"  "pl_orbsmaxerr2" 
[17] "pl_orbsmaxlim"   "pl_rade"         "pl_radeerr1"     "pl_radeerr2"    
[21] "pl_radelim"      "pl_radj"         "pl_radjerr1"     "pl_radjerr2"    
[25] "pl_radjlim"      "pl_bmasse"       "pl_bmasseerr1"   "pl_bmasseerr2"  
[29] "pl_bmasselim"    "pl_bmassj"       "pl_bmassjerr1"   "pl_bmassjerr2"  
[33] "pl_bmassjlim"    "pl_bmassprov"    "pl_orbeccen"     "pl_orbeccenerr1"
[37] "pl_orbeccenerr2" "pl_orbeccenlim"  "pl_insol"        "pl_insolerr1"   
[41] "pl_insolerr2"    "pl_insollim"     "pl_eqt"          "pl_eqterr1"     
[45] "pl_eqterr2"      "pl_eqtlim"       "ttv_flag"        "st_spectype"    
[49] "st_teff"         "st_tefferr1"     "st_tefferr2"     "st_tefflim"     
[53] "st_rad"          "st_raderr1"      "st_raderr2"      "st_radlim"      
[57] "st_mass"         "st_masserr1"     "st_masserr2"     "st_masslim"     
[61] "st_met"          "st_meterr1"      "st_meterr2"      "st_metlim"      
[65] "st_metratio"     "st_logg"         "st_loggerr1"     "st_loggerr2"    
[69] "st_logglim"      "rastr"           "ra"              "decstr"         
[73] "dec"             "sy_dist"         "sy_disterr1"     "sy_disterr2"    
[77] "sy_vmag"         "sy_vmagerr1"     "sy_vmagerr2"     "sy_kmag"        
[81] "sy_kmagerr1"     "sy_kmagerr2"     "sy_gaiamag"      "sy_gaiamagerr1" 
[85] "sy_gaiamagerr2" </code></pre>
</div>
</div>
<p>The detailed description of the columns in the data is available <a href="https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html">here</a></p>
</section>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data cleaning</h3>
<p>Selecting columns that are of interest:</p>
<ul>
<li>pl_name - planet name</li>
<li>hostname - stellar name</li>
<li>sy_snum - number of stars in the planetary system</li>
<li>sy_pnum - number of planets in the planetary system</li>
<li>discoverymethod - method through which it was discovered</li>
<li>disc_year - year in which it was discovered</li>
<li>disc_facility - facility at which it was discovered</li>
<li>pl_controv_flag - If the existence of it is controversial</li>
<li>pl_orbper - Estimated period of orbiting (in days)</li>
<li>pl_orbsmax - Length of the semi major axis of the orbit</li>
<li>pl_bmasse - Best estimated mass of the planet in units of earth’s mass</li>
<li>pl_bmassj - Best estimated mass of the planet in units of earth’s jupiter</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>planet_data <span class="ot">&lt;-</span> planet_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(pl_name, hostname, sy_snum, sy_pnum, discoverymethod, disc_year, disc_facility, pl_controv_flag, pl_orbper, pl_orbsmax, pl_bmasse, pl_bmassj)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(planet_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  pl_name    hostname sy_snum sy_pnum discover…¹ disc_…² disc_…³ pl_co…⁴ pl_or…⁵
  &lt;chr&gt;      &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 11 Com b   11 Com         2       1 Radial Ve…    2007 Xinglo…       0    326.
2 11 UMi b   11 UMi         1       1 Radial Ve…    2009 Thueri…       0    516.
3 14 And b   14 And         1       1 Radial Ve…    2008 Okayam…       0    186.
4 14 Her b   14 Her         1       2 Radial Ve…    2002 W. M. …       0   1765.
5 16 Cyg B b 16 Cyg B       3       1 Radial Ve…    1996 Multip…       0    798.
6 17 Sco b   17 Sco         1       1 Radial Ve…    2020 Lick O…       0    578.
# … with 3 more variables: pl_orbsmax &lt;dbl&gt;, pl_bmasse &lt;dbl&gt;, pl_bmassj &lt;dbl&gt;,
#   and abbreviated variable names ¹​discoverymethod, ²​disc_year,
#   ³​disc_facility, ⁴​pl_controv_flag, ⁵​pl_orbper</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># % of missing values for each column</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(<span class="fu">is.na</span>(planet_data))<span class="sc">*</span><span class="dv">100</span>   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        pl_name        hostname         sy_snum         sy_pnum discoverymethod 
       0.000000        0.000000        0.000000        0.000000        0.000000 
      disc_year   disc_facility pl_controv_flag       pl_orbper      pl_orbsmax 
       0.000000        0.000000        0.000000        3.524904        5.287356 
      pl_bmasse       pl_bmassj 
       0.440613        0.440613 </code></pre>
</div>
</div>
<p>The above chunk displays the percentage of missing values in each column. Seeing that no column is missing more than 6% of their data, we found it reasonable to conclude that there is not a significant amount of missing information (for the selected columns we chose).</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="ExoPlanetAnalysis_files/figure-html/Discovery%20method%20freq-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is a clear imbalance in the number of planets discovered by different methods. Transit and Radial velocity are the methods through which a lot of planets were discovered.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ExoPlanetAnalysis_files/figure-html/Discovery%20years-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There’s a clear indication of the increase in discoveries over time, although 2014 and 2016 were particularly successful years.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ExoPlanetAnalysis_files/figure-html/Num%20of%20Stars%20freq-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Most planetary systems are like solar systems with a single star.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of "raised" controversy flags </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(planet_data<span class="sc">$</span>pl_controv_flag <span class="sc">==</span> <span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
</div>
<p>The dataset includes information about potential controversy over a planet’s existence, in which the column <code>pl_controv_flag</code> consists of binary values (0 = no or 1 = yes) that indicate if there have been published papers that challenge the existence of the planet.</p>
<p>There are only 28 exo planets whose existence are in question so far.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<p>As mentioned earlier, there is a bias that the discovery methods tend to favor planets near the sun. We can do a hypothesis testing to check if this is significant bias.</p>
<p>To perform this analysis, we can take our own solar system as a sample (Let us assume that all the planets in our solar system are close to the sun). If there is no bias, the variance of the exo planets orbital semi major axis should be significantly different than the variance of the solar system planets orbital semi major axis.</p>
<p><span class="math display">\[H_o:\sigma_1^{2}=\sigma_2^{2}\]</span> <span class="math display">\[H_a:\sigma_1^{2}\neq\sigma_2^{2}\]</span></p>
<p>For the solar system planets orbital semi major axis,we got the data from <a href="https://windows2universe.org/our_solar_system/planets_orbits_table.html#:~:text=The%20semimajor%20axis%20the%20average,period%2C%20which%20is%20a%20year.">here</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>solar_planets <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Mercury"</span>,<span class="st">"Venus"</span>,<span class="st">"Earth"</span>,<span class="st">"Mars"</span>,<span class="st">"Jupiter"</span>,<span class="st">"Saturn"</span>,<span class="st">"Uranus"</span>,<span class="st">"Neptune"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>axis_lengths <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.3871</span>,<span class="fl">0.7233</span>,<span class="fl">1.000</span>   ,<span class="fl">1.5273</span> ,<span class="fl">5.2028</span> ,<span class="fl">9.5388</span> ,<span class="fl">19.1914</span>    ,<span class="fl">30.0611</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>solar_planets <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(solar_planets,axis_lengths)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(solar_planets) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pl_name"</span>,<span class="st">"pl_orbsmax"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>solar_planets<span class="sc">$</span>System <span class="ot">&lt;-</span> <span class="st">"Solar System"</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>exo_planets <span class="ot">&lt;-</span> planet_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(pl_name,pl_orbsmax) <span class="sc">%&gt;%</span> </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">System =</span> <span class="st">"Exo Planets"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>planets <span class="ot">&lt;-</span> <span class="fu">rbind</span>(solar_planets,exo_planets) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(pl_orbsmax))</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> pl_orbsmax <span class="sc">~</span> System, <span class="at">data =</span> planets)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df   Sum Sq Mean Sq F value Pr(&gt;F)
System         1       17      17   0.001  0.976
Residuals   4950 95382874   19269               </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="dv">4938</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>F_cr <span class="ot">&lt;-</span> <span class="fu">qf</span>(<span class="fl">0.05</span>,<span class="dv">1</span>,<span class="dv">4938</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fl">0.001</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>rejection_f_test <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">df</span>(x,df1,df2)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  y[x<span class="sc">&lt;</span>F_cr] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  y</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">8</span>)), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x){<span class="fu">df</span>(x,<span class="dv">1</span>,<span class="dv">4938</span>)},<span class="at">geom =</span> <span class="st">"line"</span>)<span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x){<span class="fu">rejection_f_test</span>(x)}, <span class="at">geom =</span> <span class="st">"area"</span>, <span class="at">fill =</span> <span class="st">"red"</span>,<span class="at">alpha =</span> <span class="fl">0.4</span>)<span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> f, <span class="at">linetype =</span> <span class="st">'dashed'</span>) <span class="sc">+</span> </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">'F'</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">'F(x)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ExoPlanetAnalysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The obtained F-Value is 0.01 and the corresponding p_value is 0.976 which is significantly higher than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The discovery methods are biased towards exo planets that are closer to the star if we define the planets in the solar system to be closer to the sun.</p>
</section>
<section id="session-info" class="level2">
<h2 class="anchored" data-anchor-id="session-info">Session info</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rvest_1.0.3     forcats_0.5.2   stringr_1.5.0   dplyr_1.0.10   
 [5] purrr_0.3.5     readr_2.1.3     tidyr_1.2.1     tibble_3.1.8   
 [9] ggplot2_3.4.0   tidyverse_1.3.2

loaded via a namespace (and not attached):
 [1] lubridate_1.9.0     assertthat_0.2.1    digest_0.6.30      
 [4] utf8_1.2.2          R6_2.5.1            cellranger_1.1.0   
 [7] backports_1.4.1     reprex_2.0.2        evaluate_0.18      
[10] httr_1.4.4          pillar_1.8.1        rlang_1.0.6        
[13] googlesheets4_1.0.1 curl_4.3.3          readxl_1.4.1       
[16] rstudioapi_0.14     rmarkdown_2.18      labeling_0.4.2     
[19] googledrive_2.0.0   htmlwidgets_1.5.4   bit_4.0.5          
[22] munsell_0.5.0       broom_1.0.1         compiler_4.2.2     
[25] modelr_0.1.10       xfun_0.35           pkgconfig_2.0.3    
[28] htmltools_0.5.3     tidyselect_1.2.0    fansi_1.0.3        
[31] crayon_1.5.2        tzdb_0.3.0          dbplyr_2.2.1       
[34] withr_2.5.0         grid_4.2.2          jsonlite_1.8.3     
[37] gtable_0.3.1        lifecycle_1.0.3     DBI_1.1.3          
[40] magrittr_2.0.3      scales_1.2.1        cli_3.4.1          
[43] stringi_1.7.8       vroom_1.6.0         farver_2.1.1       
[46] fs_1.5.2            xml2_1.3.3          ellipsis_0.3.2     
[49] generics_0.1.3      vctrs_0.5.1         tools_4.2.2        
[52] bit64_4.0.5         glue_1.6.2          hms_1.1.2          
[55] parallel_4.2.2      fastmap_1.1.0       yaml_2.3.6         
[58] timechange_0.1.1    colorspace_2.0-3    gargle_1.2.1       
[61] knitr_1.41          haven_2.5.1        </code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>